  0%|                                                                                                                 | 0/1578 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_MIL.py", line 51, in <module>
    for idx, (local_batch, local_labels) in enumerate(tqdm(data_loader)):
  File "/nobackup/xiziwang/usr/local/miniconda3/envs/tf/lib/python3.6/site-packages/tqdm/std.py", line 1091, in __iter__
    for obj in iterable:
  File "/nobackup/xiziwang/usr/local/miniconda3/envs/tf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/nobackup/xiziwang/usr/local/miniconda3/envs/tf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/nobackup/xiziwang/usr/local/miniconda3/envs/tf/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/nobackup/xiziwang/usr/local/miniconda3/envs/tf/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/nobackup/xiziwang/usr/local/miniconda3/envs/tf/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/nobackup/xiziwang/usr/local/miniconda3/envs/tf/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/nfs/nfs7/home/xiziwang/projects/stad-cvpr2020/baselines/VideoAnomalyDetection/MIL_ucf_cvpr2018/A3D_MIL_dataset.py", line 53, in __getitem__
    abnormal_clip_num = len(os.listdir(dire))
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/vision7/A3D_feat/train/anomaly/GDejMONyY4U_004166'

