  0%|                                                                                                                 | 0/1578 [00:00<?, ?it/s]1578 580
1578 1196
1578 178
  0%|                                                                                                         | 1/1578 [00:00<08:53,  2.95it/s]1578 226
1578 570
1578 1062
1578 976
1578 1292
1578 1284
1578 597
1578 194
1578 901
1578 407
1578 1247
1578 792
1578 793
1578 731
1578 28
1578 541
1578 600
1578 877
1578 1301
  1%|█▍                                                                                                      | 21/1578 [00:00<06:11,  4.19it/s]Traceback (most recent call last):
  File "train_MIL.py", line 51, in <module>
    for idx, (local_batch, local_labels) in enumerate(tqdm(data_loader)):
  File "/nobackup/xiziwang/usr/local/miniconda3/envs/tf/lib/python3.6/site-packages/tqdm/std.py", line 1091, in __iter__
    for obj in iterable:
  File "/nobackup/xiziwang/usr/local/miniconda3/envs/tf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/nobackup/xiziwang/usr/local/miniconda3/envs/tf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/nobackup/xiziwang/usr/local/miniconda3/envs/tf/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/nobackup/xiziwang/usr/local/miniconda3/envs/tf/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/nobackup/xiziwang/usr/local/miniconda3/envs/tf/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/nobackup/xiziwang/usr/local/miniconda3/envs/tf/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/nfs/nfs7/home/xiziwang/projects/stad-cvpr2020/baselines/VideoAnomalyDetection/MIL_ucf_cvpr2018/A3D_MIL_dataset.py", line 43, in __getitem__
    dire = os.path.join(os.path.join(self.root_dir, label), self.all_vids[label][index])
IndexError: list index out of range

1578 649
